-- Scratch-only seed for Build 65b Session A.5.
--
-- Authored 2026-04-29 against the scratch project
-- (jpzugbioqdjhhmuwqqeg / aaa-platform-scratch-65b-2026-04-29).
-- Run via Supabase SQL Editor or apply_migration after the full
-- migration replay (Phase 1 schema + build12..build66 + folder-names
-- fix). NEVER run this against prod — every row references
-- AAA's organization id and a scratch-only test user.
--
-- Idempotent: every INSERT uses ON CONFLICT DO NOTHING, so the file
-- is safe to re-apply if the scratch project is reset and replayed.
--
-- What this seeds:
--   * user_organizations row for the dashboard-created test user,
--     scoped to AAA with role=admin and is_active=true. This is the
--     deviation we documented when we skipped build42's prod-user seed
--     (Eric's prod user_id 7c55cdd0-... isn't in scratch's auth.users).
--   * One contact owned by AAA.
--   * One job linked to that contact, status in_progress, damage water
--     (so the FAB on /jobs/[id] has somewhere real to live).
--
-- What this does NOT seed:
--   * Organizations: AAA + Test Co are already seeded by build42.
--   * photo_tags: the 10 production tags from schema-photos.sql were
--     backfilled to AAA's org by build44. The mobile capture flow
--     fetches them via the real org-scoped query — no synthetic
--     tags needed for Session A.5 verification.
--   * user_profiles: handle_new_user (restored in build64) auto-
--     mirrors the dashboard-created auth.users row into
--     user_profiles. Don't double-insert.

-- ---------------------------------------------------------------
-- Constants. Hardcoded so re-runs are stable and the seed is
-- self-documenting. user_id was created via Supabase dashboard
-- (Authentication -> Users -> Add user) and pasted back during
-- Session A.5; password lives in Eric's password manager, not here.
-- ---------------------------------------------------------------
DO $$
DECLARE
  aaa_org_id      uuid := 'a0000000-0000-4000-8000-000000000001';
  test_user_id    uuid := 'bc93b88d-a74a-4d92-b36d-9f74bf58925f';
  test_contact_id uuid := 'c0000000-0000-4000-8000-000000000001';
  test_job_id     uuid := 'b0000000-0000-4000-8000-000000000001';
BEGIN
  -- 1. Membership: link the dashboard-created test user to AAA.
  INSERT INTO public.user_organizations (user_id, organization_id, role, is_active)
  VALUES (test_user_id, aaa_org_id, 'admin', true)
  ON CONFLICT (user_id, organization_id) DO NOTHING;

  -- 2. Contact for the test job.
  INSERT INTO public.contacts (
    id, organization_id,
    first_name, last_name, phone, email, role
  )
  VALUES (
    test_contact_id, aaa_org_id,
    'Scratch', 'Tester', '555-0100', 'scratch.tester@example.com', 'homeowner'
  )
  ON CONFLICT (id) DO NOTHING;

  -- 3. Job. job_number is auto-generated by set_job_number ->
  -- next_job_number, which uses AAA's per-org counter from build47.
  -- Status 'in_progress' + damage 'water' so the capture FAB has a
  -- realistic target.
  INSERT INTO public.jobs (
    id, organization_id, contact_id,
    status, urgency, damage_type, damage_source,
    property_address, property_type
  )
  VALUES (
    test_job_id, aaa_org_id, test_contact_id,
    'in_progress', 'urgent', 'water', 'Burst pipe under kitchen sink',
    '123 Scratch Lane, Test City, ST 00000', 'single_family'
  )
  ON CONFLICT (id) DO NOTHING;
END $$;

-- ---------------------------------------------------------------
-- Visibility check (read-only; no side effects).
-- Run after the seed to confirm row counts. Expected:
--   user_organizations: 1
--   contacts:           1
--   jobs:               1
--   photo_tags:        10  (from schema-photos.sql + build44)
-- ---------------------------------------------------------------
SELECT
  (SELECT count(*) FROM public.user_organizations
     WHERE user_id = 'bc93b88d-a74a-4d92-b36d-9f74bf58925f')      AS uo_count,
  (SELECT count(*) FROM public.contacts
     WHERE id = 'c0000000-0000-4000-8000-000000000001')            AS contact_count,
  (SELECT count(*) FROM public.jobs
     WHERE id = 'b0000000-0000-4000-8000-000000000001')            AS job_count,
  (SELECT count(*) FROM public.photo_tags
     WHERE organization_id = 'a0000000-0000-4000-8000-000000000001') AS tag_count;
